FROM node:12.13.0
WORKDIR /usr/src/nuxt
ENV HOST 0.0.0.0
COPY . . 
COPY production.env .env
COPY production.app.html app.html

RUN npm config set registry https://registry.npm.taobao.org
RUN npm install
RUN npm run build 

EXPOSE 3000
CMD ["npm","start"]