FROM node:10.16.3-buster
WORKDIR /usr/src/nuxt
ENV NODE_ENV=production
ENV HOST 0.0.0.0
COPY . . 

RUN npm config set registry https://registry.npm.taobao.org
RUN npm install
RUN npm run build 

EXPOSE 3000
CMD ["npm","start"]