server:
  port: 3002
spring:
  elasticsearch:
    rest:
      uris: 139.198.189.114:9200
      username: elastic
      password: heshenghao
      connection-timeout: 20000
      read-timeout: 30000
  oss:
    stsEndpoint: sts.cn-hangzhou.aliyuncs.com
    endpoint: http://oss-accelerate.aliyuncs.com
    urlPre: https://shuxie.oss-accelerate.aliyuncs.com/
    bucketName: shuxie
    accessKeyId: LTAI4GDTDQm93qwQFzu9nz8a
    accessKeySecret: IoTPd2UEd7Sx9i1USc1cfrT44C1VZQ
    stsAccessKeyId: LTAI4GDqHM5Q3DXHb9PLwy4S
    stsAccessKeySecret: OTH3ifR66TqHDbrT8Qc5m8JgppPBKg
  application:
    name: siques-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
    url: jdbc:mysql://127.0.0.1:3306/nest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  redis:
    host: 139.198.176.14
    port: 6379
    database: 4
    expiration: 1800
    password: heshenghao
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

  global-config:
    banner: false
  type-aliases-package: cn.siques.backend.dao
public-key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkF9SyMHeGAsLMwbPsKj/
  xpEtS0iCe8vTSBnIGBDZKmB3ma20Ry0Uzn3m+f40RwCXlxnUcvTw7ipoz0tMQERQ
  b3X4DkYCJXPK6pAD+R9/J5odEwrO2eysByWfcbMjsZw2u5pH5hleMS0YqkrGQOxJ
  pzlEcKxMePU5KYTbKUJkhOYPY+gQr61g6lF97WggSPtuQn1srT+Ptvfw6yRC4bdI
  0zV5emfXjmoLUwaQTRoGYhOFrm97vpoKiltSNIDFW01J1Lr+l77ddDFC6cdiAC0H
  5/eENWBBBTFWya8RlBTzHuikfFS1gP49PZ6MYJIVRs8p9YnnKTy7TVcGKY3XZMCA
  mwIDAQAB
  -----END PUBLIC KEY-----